dns_cache: Fix build errors on Android
Compiling gwproxy on Android results in these errors:

  src/gwproxy/dns_cache.c:138:19: error: incomplete definition of type 'const struct sockaddr_in'
    138 |                         memcpy(i4b, &i4->sin_addr, 4);
        |                                      ~~^
  src/gwproxy/dns_cache.c:131:16: note: forward declaration of 'struct sockaddr_in'
    131 |                 const struct sockaddr_in *i4;
        |                              ^
  src/gwproxy/dns_cache.c:145:19: error: incomplete definition of type 'const struct sockaddr_in6'
    145 |                         memcpy(i6b, &i6->sin6_addr, 16);
        |                                      ~~^
  src/gwproxy/dns_cache.c:130:16: note: forward declaration of 'struct sockaddr_in6'
    130 |                 const struct sockaddr_in6 *i6;
        |                              ^
  2 errors generated.
  make: *** [Makefile:123: src/gwproxy/dns_cache.c.o] Error 1
  make: *** Waiting for unfinished jobs....

Include <arpa/inet.h> to fix it.

Fixes: b88e0ff24816 ("gwproxy/dns_cache: Initial DNS cache rework")
Signed-off-by: Alviro Iskandar Setiawan <alviro.iskandar@gnuweeb.org>