configure: Add '-Wno-format-truncation' flag
Avoid false positive warning where size-limited '*printf' functions
are used as a length counter.

  In file included from /usr/include/stdio.h:980,
                   from src/gwproxy/http1.c:11:
  In function ‘vsnprintf’,
      inlined from ‘gwnet_http_hdr_fields_addf’ at src/gwproxy/http1.c:916:6:
  /usr/include/x86_64-linux-gnu/bits/stdio2.h:68:10: error: null format string [-Werror=format-truncation=]
     68 |   return __builtin___vsnprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     69 |                                     __glibc_objsize (__s), __fmt, __ap);
        |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors

This is not very useful warning. Just disable it.

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>