dns_cache: Fix missing time_t type when building on musl env
When building on musl libc environment, it yields the following error:

  In file included from src/gwproxy/dns.c:10:
  src/gwproxy/dns_cache.h:118:32: error: unknown type name 'time_t'; did you mean 'size_t'?
    118 |     const struct addrinfo *ai, time_t expired_at);
        |                                ^~~~~~
        |                                size_t

Fix it by including time.h in dns_cache.h

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>