Makefile: Fix build errors on tests
Something is wrong with the shared lib. Not sure what's going wrong here:

  ammarfaizi2@integral2:~/p/gwproxy$ make test
  gcc -ggdb3 -rdynamic -O2 -fpic -fPIC -o src/gwproxy/tests/dns.t src/gwproxy/tests/dns.c.o libgwdns.so -lpthread
  /usr/bin/ld: src/gwproxy/tests/dns.c.o: in function `test_basic_dns_multiple_requests':
  /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:77: undefined reference to `gwp_dns_ctx_init'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:84: undefined reference to `gwp_dns_queue'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:101: undefined reference to `gwp_dns_entry_put'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:102: undefined reference to `gwp_dns_ctx_free'
  /usr/bin/ld: src/gwproxy/tests/dns.c.o: in function `test_dns_cache':
  /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:114: undefined reference to `gwp_dns_ctx_init'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:118: undefined reference to `gwp_dns_queue'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:128: undefined reference to `gwp_dns_entry_put'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:130: undefined reference to `gwp_dns_cache_lookup'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:134: undefined reference to `gwp_dns_cache_lookup'
  /usr/bin/ld: /home/ammarfaizi2/p/gwproxy/src/gwproxy/tests/dns.c:136: undefined reference to `gwp_dns_ctx_free'
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:116: src/gwproxy/tests/dns.t] Error 1
  ammarfaizi2@integral2:~/p/gwproxy$

A temporary fix, link the library statically instead of dynamically via
*.so files. It needs to actually test the *.so file, but I don't want
to touch it for now. The problem is not very obvious.

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>