configure: Fix liburing include path
When building on a system where liburing.h is not in the include path
of the current system, it will yield the following errors:

   ./src/gwproxy/gwproxy.h:18:10: fatal error: liburing.h: No such file or directory
      18 | #include <liburing.h>
         |          ^~~~~~~~~~~~
   In file included from src/gwproxy/gwproxy.c:7:
   ./src/gwproxy/gwproxy.h:18:10: fatal error: liburing.h: No such file or directory
      18 | #include <liburing.h>
         |          ^~~~~~~~~~~~
   In file included from ./src/gwproxy/ev/io_uring.h:8,
                  from src/gwproxy/ev/io_uring.c:11:
   ./src/gwproxy/gwproxy.h:18:10: fatal error: liburing.h: No such file or directory
      18 | #include <liburing.h>
         |          ^~~~~~~~~~~~

Found this on GitHub Actions CI. Apparently, I never saw this on my
local machine because I have /usr/include/liburing.h file installed.

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>