github: Add 'fetch-depth: 0' to codespell target
When pushing more than one commits, it only knows the HEAD commit
because by default it performs 'git clone' with --depth=1:

  Run git checkout 7f2c098590fe;
  error: pathspec '7f2c098590fe' did not match any file(s) known to git

Add 'fetch-depth: 0' to clone the whole repository.

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>